[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/downloads"
  to = "/.netlify/functions/downloads"
  status = 200

[[redirects]]
  from = "/api/contact-requests"
  to = "/.netlify/functions/contact-requests"
  status = 200

[[redirects]]
  from = "/painel"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-login.html"
  status = 200
